package com.msjavasolutions.employeeprofile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-02T11:48:58.484-05:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://msjavasolutions.com/employeeProfile", name = "EmployeeProfilePortType")
@XmlSeeAlso({ObjectFactory.class, com.msjavasolutions.employeeprofile.schema.employeeprofile.ObjectFactory.class})
public interface EmployeeProfilePortType {

    @WebMethod(operationName = "GetEmployeeProfile", action = "urn:GetEmployeeProfile")
    @RequestWrapper(localName = "GetEmployeeProfile", targetNamespace = "http://msjavasolutions.com/employeeProfile", className = "com.msjavasolutions.employeeprofile.GetEmployeeProfile")
    @ResponseWrapper(localName = "GetEmployeeProfileResponse", targetNamespace = "http://msjavasolutions.com/employeeProfile", className = "com.msjavasolutions.employeeprofile.GetEmployeeProfileResponse")
    @WebResult(name = "EmployeeProfile", targetNamespace = "http://msjavasolutions.com/employeeProfile")
    public com.msjavasolutions.employeeprofile.schema.employeeprofile.EmployeeProfile getEmployeeProfile(
        @WebParam(name = "employeeName", targetNamespace = "http://msjavasolutions.com/employeeProfile")
        java.lang.String employeeName
    );
}
